version: '3.8'
services:
    nginx:
        image: nginx:latest
        container_name: http-server
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app

    php:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: php-backend
        env_file: ./environment/mysql.env
        volumes:
            - ./app:/app

    mysql:
        image: mariadb:latest
        container_name: database
        env_file: ./environment/mysql.env
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    mysqldata: {}